from . import credit
from . import documents
from . import product_category
from . import tipo_credito
from . import lineas_credito
from . import cuotas
from . import sale_order
from . import payments
from . import account
from . import res_partner
from . import logo_recibo
from . import res_config_settings